"""initial schema

Revision ID: 3f90bf26be58
Revises: 
Create Date: 2026-08-31 18:37:26.370488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f90bf26be58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_prices_stock_id'), 'daily_prices', ['stock_id'], unique=False)
    op.create_index(op.f('ix_daily_prices_trade_date'), 'daily_prices', ['trade_date'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('fundamental_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('long_term_score', sa.Float(), nullable=True),
    sa.Column('short_term_score', sa.Float(), nullable=True),
    sa.Column('long_term_label', sa.String(length=20), nullable=True),
    sa.Column('short_term_label', sa.String(length=20), nullable=True),
    sa.Column('explanation', sa.String(length=500), nullable=True),
    sa.Column('excluded_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_computed_at'), 'scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_scores_stock_id'), 'scores', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_stock_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_computed_at'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_daily_prices_trade_date'), table_name='daily_prices')
    op.drop_index(op.f('ix_daily_prices_stock_id'), table_name='daily_prices')
    op.drop_table('daily_prices')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
