"""add news_corroborations table

Revision ID: eb45cee47be1
Revises: 3f90bf26be58
Create Date: 2026-09-02 20:13:11.465392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb45cee47be1'
down_revision: Union[str, Sequence[str], None] = '3f90bf26be58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_corroborations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('bull_case', sa.Text(), nullable=False),
    sa.Column('bear_case', sa.Text(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_corroborations_computed_at'), 'news_corroborations', ['computed_at'], unique=False)
    op.create_index(op.f('ix_news_corroborations_stock_id'), 'news_corroborations', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_corroborations_stock_id'), table_name='news_corroborations')
    op.drop_index(op.f('ix_news_corroborations_computed_at'), table_name='news_corroborations')
    op.drop_table('news_corroborations')
    # ### end Alembic commands ###
